### ISSUE TITLE
Doesn't show the game/categories on anywhere

### ISSUE THREAD

**Issue by U1s2e3r4n5a6m7e** [23rd/TwitchPotPlayer#18]
![0](https://user-images.githubusercontent.com/50280168/67906761-adb4af80-fb86-11e9-9ceb-f36ab8e7ed84.png)

Win 10, x64
Latest v. of PotPlayer x64

I tried to reinstall the extension / extension&potplayer
showBitrate= (works)
showFPS= (works)

I guess this variables doesn't work for me :(
gameInTitle=1
gameInContent=1

Note: Header title, was same as in the description(Coffee + Painting?) before I rename as "Test" on playlist.

**Comment by 23rd** [comment]
Yeah, yeah, it's not working now.

The latest version of the Twitch API gives the game id as an answer instead of the name of the game. Now to get the name of the game I need to make an additional request, which slows down the whole process of opening the stream. I thought it was a pretty little used feature, but it seems like I have to add it.

**Comment by 23rd** [comment]
Should be fixed now I think.

**Comment by U1s2e3r4n5a6m7e** [comment]
Thank you, master :)
